version: "3.8"

services:

  registry:
    container_name: registry
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - ./data:/var/lib/registry
    restart: unless-stopped

  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:2
    ports:
      - "5080:80"
    environment:
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: "Local Docker Registry"
      NGINX_PROXY_PASS_URL: http://registry:5000
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
    depends_on:
      - registry
    restart: unless-stopped